// One fixture site per supported theme, generated by Hexo 8 from the two posts
// in fixtures/themes/*.md with the theme's current release and no theme config
// beyond the defaults. Each test recovers the site with theme auto-detection
// and checks: the theme was named, both post bodies convert back to the source
// Markdown, the front matter carries what the page showed, and `verify` accepts
// the theme's pages against the NexT rendering of the same posts (the two sites
// in a real recovery run different themes: the old one and NexT).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import * as cheerio from 'cheerio';
import { THEMES, THEME_NAMES, detectTheme, themeVersion } from '../src/themes.js';
import { recover, defaultOptions, resolveDate } from '../src/recover.js';
import { verify } from '../src/verify.js';

const FIX = path.join(path.dirname(new URL(import.meta.url).pathname), 'fixtures', 'themes');
const norm = (s) => s.replace(/\s+/g, ' ').trim();
const source = (name) => norm(fs.readFileSync(path.join(FIX, name), 'utf8')
  .split('---\n').slice(2).join('---\n').replace('<!-- more -->\n\n', ''));
const SRC1 = source('recursive-descent.md');
const SRC2 = source('hello-again.md');
const tmp = () => fs.mkdtempSync(path.join(os.tmpdir(), 'hexo-recover-themes-'));
const post = (theme, p) => path.join(FIX, theme, p, 'index.html');

/**
 * What each theme's pages give away. `date` is the post's local time when the
 * theme prints one (or a timestamp with an offset), otherwise the UTC instant
 * from Open Graph in ISO form. `version` is '' where the theme prints none.
 */
const EXPECT = {
  next:      { version: '8.29.0', date: '2018-09-06 21:39:10', updated: '2026-09-04 10:52:21' },
  landscape: { version: '',       date: '2018-09-06T13:39:10.000Z', updated: '2026-09-04T02:52:21.000Z' },
  butterfly: { version: '5.7.0',  date: '2018-09-06T13:39:10.000Z', updated: '2026-09-04T02:52:21.000Z' },
  fluid:     { version: '1.9.9',  date: '2018-09-06 21:39:10', updated: '2026-09-04T02:52:21.000Z' },
  icarus:    { version: '',       date: '2018-09-06T13:39:10.000Z', updated: '2026-09-04T02:52:21.000Z' },
  volantis:  { version: '6.8.3',  date: '2018-09-06 21:39:10', updated: '2026-09-04 10:52:21' },
  stellar:   { version: '1.44.0', date: '2018-09-06 21:39:10', updated: '2026-09-04 10:52:21' },
  keep:      { version: '',       date: '2018-09-06 21:39:10', updated: null },
  redefine:  { version: '2.9.0',  date: '2018-09-06 21:39:10', updated: '2026-09-04 10:52:21' },
};

test('every theme in the table has a fixture and an expectation', () => {
  assert.deepEqual(Object.keys(EXPECT).sort(), [...THEME_NAMES].sort());
  for (const t of THEME_NAMES) assert.ok(fs.existsSync(post(t, '2018/09/06/recursive-descent')), `${t} fixture`);
});

for (const theme of THEME_NAMES) {
  test(`${theme}: detected, posts convert back to the source, meta read from the page`, () => {
    const html = fs.readFileSync(post(theme, '2018/09/06/recursive-descent'), 'utf8');
    const $ = cheerio.load(html);
    assert.equal(detectTheme($, html), theme);
    assert.equal(themeVersion(theme, html + fs.readFileSync(path.join(FIX, theme, 'index.html'), 'utf8')), EXPECT[theme].version);
    // The body selector must single out one element on the post page.
    assert.equal($(THEMES[theme].body).length, 1, `${THEMES[theme].body} matches once`);

    const out = tmp();
    const rep = recover(path.join(FIX, theme), out, defaultOptions());
    assert.equal(rep.site.theme, theme);
    assert.equal(rep.public.length, 2);
    assert.equal(rep.about, true, 'about page recovered');
    assert.ok(rep.site.excerptLength > 0, 'index excerpts measured');

    const md1 = fs.readFileSync(path.join(out, 'source', '_posts', 'recursive-descent.md'), 'utf8').split('---\n');
    const md2 = fs.readFileSync(path.join(out, 'source', '_posts', 'hello-again.md'), 'utf8').split('---\n');
    assert.equal(norm(md1.slice(2).join('---\n')), SRC1);
    assert.equal(norm(md2.slice(2).join('---\n')), SRC2);

    const fm = md1[1];
    assert.match(fm, /^title: "Writing a Recursive Descent Parser"$/m);
    assert.match(fm, new RegExp(`^date: ${EXPECT[theme].date.replace('.', '\\.')}$`, 'm'));
    if (EXPECT[theme].updated) assert.match(fm, new RegExp(`^updated: ${EXPECT[theme].updated.replace('.', '\\.')}$`, 'm'));
    else assert.doesNotMatch(fm, /^updated:/m);
    assert.match(fm, /^categories:\n  - "Compilers"$/m);
    assert.ok(fm.includes('  - "parser"') && fm.includes('  - "javascript"'), 'both tags');
    assert.doesNotMatch(fm, /"Grammar"|"Lab Blog"/, 'no heading or site name leaked into tags');
  });

  test(`${theme}: verify accepts its pages against the NexT rendering`, () => {
    const lines = [];
    assert.equal(verify(path.join(FIX, theme), path.join(FIX, 'next'), null, (s) => lines.push(s)), 0, lines.join('\n'));
    assert.ok(lines.some((l) => /^posts compared\s*: 2$/.test(l)));
  });
}

test('explicit --theme wins over detection, unknown theme is an error', () => {
  const out = tmp();
  const opt = defaultOptions();
  opt.theme = 'landscape';
  assert.throws(() => recover(path.join(FIX, 'butterfly'), out, opt), /no element matches "\.article-entry"/);
  opt.theme = 'nope';
  assert.throws(() => recover(path.join(FIX, 'butterfly'), out, opt), /unknown theme "nope"/);
});

test('an unrecognised theme asks for --body-selector, and the override works', () => {
  const root = tmp();
  fs.mkdirSync(path.join(root, 'site', '2020', '01', '02', 'p'), { recursive: true });
  fs.writeFileSync(path.join(root, 'site', '2020', '01', '02', 'p', 'index.html'),
    '<html><head><meta property="og:title" content="P"></head><body><main class="x"><p>hi</p></main></body></html>');
  assert.throws(() => recover(path.join(root, 'site'), path.join(root, 'out'), defaultOptions()), /could not tell which theme/);
  const opt = defaultOptions();
  opt.selectors = { body: 'main.x' };
  const rep = recover(path.join(root, 'site'), path.join(root, 'out2'), opt);
  assert.equal(rep.public.length, 1);
  assert.equal(rep.public[0].title, 'P');
});

test('resolveDate: offset, visible local time (with and without seconds), UTC fallback', () => {
  assert.equal(resolveDate('2018-09-06T13:39:10.000Z', ['2018-09-06T21:39:10+08:00']), '2018-09-06 21:39:10');
  assert.equal(resolveDate('2018-09-06T13:39:10.000Z', ['2018-09-06 21:39:10']), '2018-09-06 21:39:10');
  assert.equal(resolveDate('2018-09-06T13:39:10.000Z', ['2018-09-06 21:39']), '2018-09-06 21:39:10');
  assert.equal(resolveDate('2026-09-04T02:52:21.727Z', ['2026-09-04 10:52:21']), '2026-09-04 10:52:21');
  // A time that is not the same instant up to a timezone offset is not this post's date.
  assert.equal(resolveDate('2018-09-06T13:39:10.000Z', ['2018-09-06 21:41']), '2018-09-06T13:39:10.000Z');
  assert.equal(resolveDate('2018-09-06T13:39:10.000Z', []), '2018-09-06T13:39:10.000Z');
  assert.equal(resolveDate('', ['2018-09-06 21:39']), '2018-09-06 21:39:00');
  assert.equal(resolveDate('', []), null);
});
